language: clojure
install: lein install
before_script:
  - psql -c 'create database testprojects;' -U postgres
script: lein midje
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  allow_failures:
    - oraclejdk7
    - oraclejdk8
